import Head from 'next/head';
import { app } from '@/script/firebase';
import { useEffect } from 'react';
import styles from '@/styles/Home.module.css'
import {
    getAuth,
    signInWithEmailAndPassword,
    GoogleAuthProvider,
    GithubAuthProvider,
    signInWithPopup,
    TwitterAuthProvider,
    sendSignInLinkToEmail
} from 'firebase/auth'
import { useState } from 'react';
export default function Register() {
    const auth = getAuth();
    const googleProvider = new GoogleAuthProvider();
    const githubProvider = new GithubAuthProvider();
    const twitter = new TwitterAuthProvider();
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    // const signUp = () => {
    //     signInWithEmailAndPassword(auth, email, password)
    //         .then((response) => {
    //             console.log(response.user)
    //             sessionStorage.setItem('Token', response.user.accessToken);
    //         })
    //         .catch(err => {
    //             alert('Cannot Log in')
    //         })
    // }

    const signUpWithGoogle = () => {
        signInWithPopup(auth, googleProvider)
            .then((response) => {
                sessionStorage.setItem('Token', response.user.accessToken)
                console.log(response.user.email)
            })
    }
    const signUpWithGithub = () => {
        signInWithPopup(auth, githubProvider)
            .then((response) => {
                sessionStorage.setItem('Token', response.user.accessToken)
                console.log(response.user)
            })
    }

    const signUpWithTwitter = () => {
        signInWithPopup(auth, twitter)
            .then((response) => {
                sessionStorage.setItem('Token', response.user.accessToken)
                console.log(response.user)
            })
    }
    const actionCodeSettings = {
        // URL you want to redirect back to. The domain (www.example.com) for this
        // URL must be in the authorized domains list in the Firebase Console.
        url: 'http://ronnapat.com/',
        // This must be true.
        handleCodeInApp: true,
      };
    const emaillink = () => {
        sendSignInLinkToEmail(auth, email, actionCodeSettings)
            .then((response) => {
                sessionStorage.setItem('Token', response.user.accessToken);
                localStorage.setItem('emailForSignIn', email);
                console.log(response.user)
            })
            .catch((err) => {
                console.log(err)
                // ...
            });
    }

    useEffect(() => {
        let token = sessionStorage.getItem('Token')

        if(token){
            alert('You are login')
        }
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Next CRUD AUTH</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Login</h1>

                <input
                    placeholder='Email'
                    className={styles.inputBox}
                    onChange={(event) => setEmail(event.target.value)}
                    value={email}
                    type='email'
                />
                <input
                    placeholder='Password'
                    className={styles.inputBox}
                    onChange={(event) => setPassword(event.target.value)}
                    value={password}
                    type='password'
                />

                <button
                    className={styles.button}
                    onClick={emaillink}
                >Sign In</button>
                <hr />
                <button
                    className={styles.googleAlt}
                    onClick={signUpWithGoogle}>
                    Sign Up with Google
                </button>
                <hr />
                <hr />
                <button
                    onClick={signUpWithGithub}
                    className={styles.googleAlt}>
                    Sign Up with Github
                </button>
                <button
                    onClick={signUpWithTwitter}
                    className={styles.googleAlt}>
                    Sign Up with Github
                </button>
            </main>
        </div>
    )
}