export const facebook = "pieronnapat"
export const twitter = "ronnapatp"
export const github = "ronnapatp"
export const mail = "me@ronnapat.com"
export const discord = "https://discord.com/users/746664242907971601"